apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
  namespace: expense 
  labels:
    app: mysql
    tier: db
    project: expense
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        tier: db
        project: expense
    spec: 
      containers: 
      - name: mysql
        image: joindevops/myswl:v1
        ports:
---
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306 # service port
    targetPort: 3306 # container port               